version: "3.9"

services:
  frontend:
    build: ./frontend
    container_name: distenda-frontend
    ports:
      - "3000:80"  # React user UI chạy ở localhost:3000

  frontendadmin:
    build: ./frontendadmin
    container_name: distenda-frontendadmin
    ports:
      - "3002:80"  # React admin UI chạy ở localhost:3002

  backend:
    build: ./backend
    container_name: distenda-backend
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "3001:3001"  # API chạy ở localhost:3001
    env_file:
      - ./backend/.env
